// Demo data used by `npm run seed`.
// Pictures are real photos (Open Images, CC BY 2.0): product photos in /uploads/photos (see its CREDITS.md),
// market and farm photos in /uploads/places (see its CREDITS.md).

const thumb = (name) => `/uploads/photos/thumbs/${name}.webp`; // 320 x 320 square, for icons and logos

export const PASSWORDS = {
  admin: 'Admin@123',
  farmer: 'Farmer@123',
  customer: 'Customer@123',
};

// Cities in the city dropdowns (cities collection). Latitude/longitude = city centre.
export const cities = [
  { name: 'Karachi', province: 'Sindh', latitude: 24.8607, longitude: 67.0011 },
  { name: 'Lahore', province: 'Punjab', latitude: 31.5204, longitude: 74.3587 },
  { name: 'Islamabad', province: 'Islamabad Capital Territory', latitude: 33.6844, longitude: 73.0479 },
  { name: 'Rawalpindi', province: 'Punjab', latitude: 33.5651, longitude: 73.0169 },
  { name: 'Hyderabad', province: 'Sindh', latitude: 25.396, longitude: 68.3578 },
  { name: 'Faisalabad', province: 'Punjab', latitude: 31.4504, longitude: 73.135 },
  { name: 'Multan', province: 'Punjab', latitude: 30.1575, longitude: 71.5249 },
  { name: 'Peshawar', province: 'Khyber Pakhtunkhwa', latitude: 34.0151, longitude: 71.5249 },
  { name: 'Quetta', province: 'Balochistan', latitude: 30.1798, longitude: 66.975 },
];

export const admin = { name: 'MarketLink Admin', email: 'admin@marketlink.com', phone: '+92 300 0000000', address: 'MarketLink HQ, F.B. Area, Karachi', city: 'Karachi' };

export const categories = [
  { key: 'veg', name: 'Vegetables', nameUr: 'سبزیاں', description: 'Seasonal vegetables harvested for market day.', icon: thumb('capsicum-mix'), image: '/uploads/photos/categories/vegetables.webp', color: '#E4F3D8', sortOrder: 1 },
  { key: 'fruit', name: 'Fruits', nameUr: 'پھل', description: 'Orchard-fresh and tree-ripened fruit.', icon: thumb('red-apples'), image: '/uploads/photos/categories/fruits.webp', color: '#FFE4DA', sortOrder: 2 },
  { key: 'dairy', name: 'Dairy & Eggs', nameUr: 'دودھ اور انڈے', description: 'Fresh milk, cheese, butter and free-range eggs.', icon: thumb('desi-eggs'), image: '/uploads/photos/categories/dairy-eggs.webp', color: '#E3EEFB', sortOrder: 3 },
  { key: 'bakery', name: 'Baked Goods', nameUr: 'بیکری', description: 'Breads and treats baked the morning of the market.', icon: thumb('country-sourdough-loaf'), image: '/uploads/photos/categories/baked-goods.webp', color: '#F8E8CF', sortOrder: 4 },
  { key: 'herbs', name: 'Herbs & Greens', nameUr: 'ہرے پتے اور جڑی بوٹیاں', description: 'Leafy greens and fragrant herbs.', icon: thumb('coriander-dhania'), image: '/uploads/photos/categories/herbs-greens.webp', color: '#DAF1E3', sortOrder: 5 },
  { key: 'honey', name: 'Honey & Preserves', nameUr: 'شہد اور مربے', description: 'Raw honey, jams, chutneys and pickles.', icon: thumb('wild-sidr-honey'), image: '/uploads/photos/categories/honey-preserves.webp', color: '#FFF0C2', sortOrder: 6 },
  { key: 'grains', name: 'Grains & Pulses', nameUr: 'اناج اور دالیں', description: 'Stone-ground flour, rice, lentils and nuts.', icon: thumb('red-kidney-beans'), image: '/uploads/photos/categories/grains-pulses.webp', color: '#F1EAD6', sortOrder: 7 },
  { key: 'flowers', name: 'Flowers & Plants', nameUr: 'پھول اور پودے', description: 'Cut flowers and potted plants.', icon: thumb('desi-rose-bouquet'), image: '/uploads/photos/categories/flowers-plants.webp', color: '#FBE1EE', sortOrder: 8 },
];

// Days: 0 = Sunday ... 6 = Saturday
export const markets = [
  {
    key: 'clifton',
    name: 'Clifton Seaview Farmers Market',
    description: 'A breezy weekend market near the sea front with the widest choice of vegetables, bakery and flowers in the city.',
    descriptionUr: "سمندر کے کنارے ہوادار ہفتہ وار مارکیٹ، جہاں شہر میں سبزیوں، بیکری اور پھولوں کا سب سے بڑا انتخاب ملتا ہے۔",
    address: 'Block 2, Clifton (near Boat Basin), Karachi',
    city: 'Karachi',
    latitude: 24.8195,
    longitude: 67.0306,
    operatingDays: [6, 0],
    openTime: '07:00',
    closeTime: '13:00',
    image: '/uploads/places/markets/clifton.webp',
  },
  {
    key: 'dha',
    name: 'DHA Phase 6 Weekend Market',
    description: 'Friday and Sunday market in Bukhari Commercial, loved for dairy, honey and ready-to-eat bakes.',
    descriptionUr: "بخاری کمرشل میں جمعہ اور اتوار کی مارکیٹ، جو دودھ کی اشیاء، شہد اور تیار بیکری کے لیے مشہور ہے۔",
    address: 'Bukhari Commercial, DHA Phase 6, Karachi',
    city: 'Karachi',
    latitude: 24.7934,
    longitude: 67.066,
    operatingDays: [5, 0],
    openTime: '08:00',
    closeTime: '14:00',
    image: '/uploads/places/markets/dha.webp',
  },
  {
    key: 'gulshan',
    name: 'Gulshan Sunday Kisan Bazaar',
    description: 'A big, lively bazaar where farmers from Gadap and Malir bring fruit and vegetables straight from the field.',
    descriptionUr: "ایک بڑا اور رونق بھرا بازار جہاں گڈاپ اور ملیر کے کسان کھیت سے سیدھے پھل اور سبزیاں لاتے ہیں۔",
    address: 'Block 13-D, Gulshan-e-Iqbal (near Maskan Chowrangi), Karachi',
    city: 'Karachi',
    latitude: 24.9206,
    longitude: 67.0935,
    operatingDays: [0, 3],
    openTime: '07:00',
    closeTime: '15:00',
    image: '/uploads/places/markets/gulshan.webp',
  },
  {
    key: 'nazimabad',
    name: 'North Nazimabad Evening Green Market',
    description: 'An evening market for after-work shopping: herbs, greens, grains and pulses.',
    descriptionUr: "دفتر کے بعد خریداری کے لیے شام کی مارکیٹ: جڑی بوٹیاں، ہری سبزیاں، اناج اور دالیں۔",
    address: 'Block H, North Nazimabad (Hyderi), Karachi',
    city: 'Karachi',
    latitude: 24.9387,
    longitude: 67.0433,
    operatingDays: [3, 6],
    openTime: '16:00',
    closeTime: '21:00',
    image: '/uploads/places/markets/nazimabad.webp',
  },
  {
    key: 'bahadurabad',
    name: 'Bahadurabad Fresh Friday Market',
    description: 'Compact neighbourhood market around the Bahadurabad roundabout with fruit, flowers and bakery.',
    descriptionUr: "بہادرآباد چورنگی کے آس پاس محلے کی چھوٹی مارکیٹ، جہاں پھل، پھول اور بیکری کی اشیاء ملتی ہیں۔",
    address: 'Bahadurabad Chowrangi, Bahadur Yar Jang Society, Karachi',
    city: 'Karachi',
    latitude: 24.8822,
    longitude: 67.0697,
    operatingDays: [2, 5],
    openTime: '16:00',
    closeTime: '21:00',
    image: '/uploads/places/markets/bahadurabad.webp',
  },
  {
    key: 'saddar',
    name: 'Saddar Heritage Farmers Market',
    description: 'Early-morning market near the historic Empress Market for grains, pulses and herbs.',
    descriptionUr: "تاریخی ایمپریس مارکیٹ کے قریب صبح سویرے کی مارکیٹ، اناج، دالوں اور جڑی بوٹیوں کے لیے۔",
    address: 'Near Empress Market, Saddar, Karachi',
    city: 'Karachi',
    latitude: 24.8595,
    longitude: 67.0298,
    operatingDays: [1, 4, 6],
    openTime: '06:00',
    closeTime: '12:00',
    image: '/uploads/places/markets/saddar.webp',
  },
  {
    key: 'lahore',
    name: 'Model Town Kisan Market',
    description: 'Lahore\'s favourite Sunday and Thursday market for winter vegetables, strawberries and citrus.',
    descriptionUr: "لاہور کی پسندیدہ اتوار اور جمعرات کی مارکیٹ، سردیوں کی سبزیوں، اسٹرابیری اور کینو کے لیے۔",
    address: 'Model Town Link Road, Lahore',
    city: 'Lahore',
    latitude: 31.484,
    longitude: 74.324,
    operatingDays: [0, 4],
    openTime: '07:00',
    closeTime: '13:00',
    image: '/uploads/places/markets/lahore.webp',
  },
  {
    key: 'islamabad',
    name: 'F-9 Park Weekend Market',
    description: 'Weekend market at the edge of F-9 Park with fruit from the Margalla and Murree hills.',
    descriptionUr: "ایف نائن پارک کے کنارے ہفتہ وار مارکیٹ، جہاں مارگلہ اور مری کی پہاڑیوں کے پھل ملتے ہیں۔",
    address: 'Fatima Jinnah Park (F-9), Islamabad',
    city: 'Islamabad',
    latitude: 33.7016,
    longitude: 73.026,
    operatingDays: [6, 0],
    openTime: '08:00',
    closeTime: '14:00',
    image: '/uploads/places/markets/islamabad.webp',
  },
];

// status: active (approved) | pending | suspended
export const farmers = [
  {
    key: 'malir',
    email: 'farmer@marketlink.com',
    status: 'active',
    stallName: 'Malir Green Fields',
    contactPerson: 'Ahmed Raza',
    phone: '+92 300 1234567',
    address: 'Plot 14, Malir Agricultural Belt, Karachi',
    city: 'Karachi',
    bio: 'Three generations of vegetable growers from Malir. We pick on Friday evening so everything is at its freshest for the weekend markets. No synthetic pesticides, just compost and care.',
    bioUr: "ملیر کے سبزی اگانے والوں کی تیسری نسل۔ ہم جمعہ کی شام چنائی کرتے ہیں تاکہ ہفتے کے آخر کی مارکیٹوں کے لیے سب کچھ بالکل تازہ ہو۔ کوئی مصنوعی کیڑے مار دوا نہیں، صرف نامیاتی کھاد اور توجہ۔",
    tags: ['Pesticide-free', 'Family farm', 'Picked daily'],
    logo: thumb('vine-tomatoes'),
    cover: '/uploads/places/farms/malir.webp',
    latitude: 24.8203,
    longitude: 67.0318,
    windows: [
      { market: 'clifton', day: 6, start: '08:00', end: '12:00' },
      { market: 'clifton', day: 0, start: '08:00', end: '12:00' },
      { market: 'dha', day: 5, start: '09:00', end: '13:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Vine Tomatoes', cat: 'veg', price: 180, was: 220, unit: 'kg', qty: 60, img: 'tomato', desc: 'Juicy red tomatoes ripened on the vine. Perfect for salads, karahi and chutneys.' },
      { name: 'Sweet Carrots', cat: 'veg', price: 120, unit: 'kg', qty: 45, img: 'carrot', desc: 'Crunchy winter carrots, great for gajar ka halwa or fresh juice.' },
      { name: 'Farm Potatoes', cat: 'veg', price: 90, was: 125, unit: 'kg', qty: 80, img: 'potato', desc: 'Versatile all-purpose potatoes, washed and sorted.' },
      { name: 'Red Onions', cat: 'veg', price: 140, unit: 'kg', qty: 70, img: 'onion', desc: 'Sharp, flavourful red onions from our dry fields.' },
      { name: 'Desi Cucumbers', cat: 'veg', price: 100, unit: 'kg', qty: 30, img: 'cucumber', desc: 'Small, crisp cucumbers with thin skin. Great for raita.' },
      { name: 'Purple Brinjal', cat: 'veg', price: 110, unit: 'kg', qty: 25, img: 'eggplant', desc: 'Glossy round brinjals ideal for bharta and baingan fry.' },
      { name: 'Capsicum Mix', cat: 'veg', price: 320, unit: 'kg', qty: 0, img: 'bell-pepper', desc: 'Green and red bell peppers. Sold out this week, back next harvest.', template: 20 },
      { name: 'Green Chillies', cat: 'veg', price: 240, unit: 'kg', qty: 12, img: 'chilli', desc: 'Fiery green chillies, freshly picked.' },
    ],
  },
  {
    key: 'gadap',
    email: 'orchard@marketlink.com',
    status: 'active',
    stallName: 'Gadap Orchard Co.',
    contactPerson: 'Zainab Hussain',
    phone: '+92 321 5550101',
    address: 'Gadap Town Orchards, Karachi',
    city: 'Karachi',
    bio: 'Mango, banana and melon orchards in the Gadap valley. We tree-ripen our fruit and bring it to market within a day of picking.',
    bioUr: "گڈاپ کی وادی میں آم، کیلے اور خربوزے کے باغات۔ ہم پھل درخت پر ہی پکنے دیتے ہیں اور توڑنے کے ایک دن کے اندر مارکیٹ لاتے ہیں۔",
    tags: ['Tree-ripened', 'Orchard'],
    logo: thumb('sindhri-mangoes'),
    cover: '/uploads/places/farms/gadap.webp',
    latitude: 24.9214,
    longitude: 67.0948,
    windows: [
      { market: 'gulshan', day: 0, start: '08:00', end: '13:00' },
      { market: 'gulshan', day: 3, start: '08:00', end: '12:00' },
      { market: 'bahadurabad', day: 5, start: '16:00', end: '20:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Sindhri Mangoes', cat: 'fruit', price: 350, unit: 'kg', qty: 90, img: 'mango', desc: 'The king of fruits. Sweet, fibre-less Sindhri mangoes.' },
      { name: 'Chaunsa Mangoes', cat: 'fruit', price: 400, unit: 'kg', qty: 40, img: 'mango', desc: 'Late-season Chaunsa with rich, honey-like sweetness.' },
      { name: 'Bananas', cat: 'fruit', price: 180, unit: 'dozen', qty: 50, img: 'banana', desc: 'Naturally ripened bananas from our riverside plots.' },
      { name: 'Watermelon', cat: 'fruit', price: 70, was: 90, unit: 'kg', qty: 35, img: 'watermelon', desc: 'Crisp and sweet summer watermelons.' },
      { name: 'Cantaloupe Melon', cat: 'fruit', price: 150, unit: 'piece', qty: 20, img: 'melon', desc: 'Fragrant melons, perfect for breakfast.' },
      { name: 'Tender Coconuts', cat: 'fruit', price: 200, unit: 'piece', qty: 15, img: 'coconut', desc: 'Fresh coconuts full of sweet water.' },
      { name: 'Lemons', cat: 'fruit', price: 260, unit: 'kg', qty: 18, img: 'lemon', desc: 'Juicy desi lemons for sikanjabeen.' },
    ],
  },
  {
    key: 'thatta',
    email: 'dairy@marketlink.com',
    status: 'active',
    stallName: 'Thatta Dairy Collective',
    contactPerson: 'Imran Soomro',
    phone: '+92 333 7778899',
    address: 'Village Jhimpir Road, Thatta, Sindh',
    city: 'Karachi',
    bio: 'A cooperative of twelve small dairy families. Grass-fed buffalo and cow milk, fresh paneer and free-range eggs delivered to market on ice.',
    bioUr: "بارہ چھوٹے ڈیری خاندانوں کی کوآپریٹو۔ گھاس پر پلی بھینسوں اور گایوں کا دودھ، تازہ پنیر اور دیسی انڈے، برف میں رکھ کر مارکیٹ پہنچائے جاتے ہیں۔",
    tags: ['Cooperative', 'Grass-fed', 'Free-range'],
    logo: thumb('farm-paneer'),
    cover: '/uploads/places/farms/thatta.webp',
    latitude: 24.7942,
    longitude: 67.0671,
    windows: [
      { market: 'dha', day: 5, start: '08:00', end: '12:00' },
      { market: 'dha', day: 0, start: '08:00', end: '12:00' },
      { market: 'clifton', day: 6, start: '08:00', end: '11:00' },
    ],
    cutoff: 24,
    products: [
      { name: 'Fresh Buffalo Milk', cat: 'dairy', price: 240, unit: 'litre', qty: 60, img: 'milk', desc: 'Creamy, unhomogenised buffalo milk, chilled at milking.' },
      { name: 'Farm Paneer', cat: 'dairy', price: 1400, unit: 'kg', qty: 10, img: 'cheese', desc: 'Soft paneer made the same morning. Perfect for palak paneer.' },
      { name: 'Desi Eggs', cat: 'dairy', price: 450, unit: 'dozen', qty: 40, img: 'egg', desc: 'Free-range desi eggs with deep orange yolks.' },
      { name: 'Hand-churned Butter', cat: 'dairy', price: 900, unit: 'pack', qty: 15, img: 'butter', desc: 'Traditional makhan, lightly salted, 250 g pack.' },
      { name: 'Natural Yogurt', cat: 'dairy', price: 280, unit: 'kg', qty: 25, img: 'jar', desc: 'Thick set dahi cultured overnight in clay pots.' },
    ],
  },
  {
    key: 'bakehouse',
    email: 'bakery@marketlink.com',
    status: 'active',
    stallName: 'Karachi Artisan Bakehouse',
    contactPerson: 'Sana Mirza',
    phone: '+92 345 2223344',
    address: 'Shop 7, Khayaban-e-Shamsheer, DHA Phase 5, Karachi',
    city: 'Karachi',
    bio: 'Slow-fermented sourdough and French-style pastries baked in small batches before sunrise. We use locally milled flour and Thatta butter.',
    bioUr: "آہستہ خمیر ہونے والی ساؤر ڈو روٹی اور فرانسیسی طرز کی پیسٹریاں، جو طلوعِ آفتاب سے پہلے تھوڑی تھوڑی مقدار میں پکائی جاتی ہیں۔ ہم مقامی چکی کا آٹا اور ٹھٹہ کا مکھن استعمال کرتے ہیں۔",
    tags: ['Sourdough', 'Small batch'],
    logo: thumb('butter-croissants'),
    cover: '/uploads/places/farms/bakehouse.webp',
    latitude: 24.8188,
    longitude: 67.0296,
    windows: [
      { market: 'clifton', day: 6, start: '08:00', end: '12:00' },
      { market: 'clifton', day: 0, start: '08:00', end: '12:00' },
      { market: 'bahadurabad', day: 2, start: '16:00', end: '20:00' },
    ],
    cutoff: 18,
    products: [
      { name: 'Country Sourdough Loaf', cat: 'bakery', price: 950, unit: 'loaf', qty: 20, img: 'bread', desc: '36-hour fermented sourdough with a crackly crust.' },
      { name: 'Classic Baguette', cat: 'bakery', price: 450, unit: 'piece', qty: 25, img: 'baguette', desc: 'Crisp, airy French baguette.' },
      { name: 'Butter Croissants', cat: 'bakery', price: 1200, unit: 'box', qty: 12, img: 'croissant', desc: 'Box of 4 flaky, all-butter croissants.' },
      { name: 'Whole Wheat Naan', cat: 'bakery', price: 300, unit: 'pack', qty: 30, img: 'flatbread', desc: 'Pack of 6 soft whole-wheat naans.' },
      { name: 'Sesame Bagels', cat: 'bakery', price: 800, unit: 'pack', qty: 10, img: 'bagel', desc: 'Pack of 4 chewy sesame bagels.' },
      { name: 'Seasonal Fruit Pie', cat: 'bakery', price: 1800, unit: 'piece', qty: 6, img: 'pie', desc: 'Buttery pie filled with fruit of the week.' },
      { name: 'Oat Chocolate Cookies', cat: 'bakery', price: 650, unit: 'box', qty: 15, img: 'cookie', desc: 'Box of 6 chewy oat and dark chocolate cookies.' },
    ],
  },
  {
    key: 'herbs',
    email: 'herbs@marketlink.com',
    status: 'active',
    stallName: 'Hyderabad Herb Garden',
    contactPerson: 'Farhan Qureshi',
    phone: '+92 301 4445566',
    address: 'Latifabad Unit 8, Hyderabad',
    city: 'Karachi',
    bio: 'Leafy greens and fragrant herbs grown in raised beds and harvested the same afternoon for the evening markets.',
    bioUr: "اونچی کیاریوں میں اگائی گئی ہرے پتوں والی سبزیاں اور خوشبودار جڑی بوٹیاں، جو شام کی مارکیٹوں کے لیے اسی دوپہر کاٹی جاتی ہیں۔",
    tags: ['Same-day harvest', 'Hydro-greens'],
    logo: thumb('fresh-mint-podina'),
    cover: '/uploads/places/farms/herbs.webp',
    latitude: 24.9395,
    longitude: 67.0441,
    windows: [
      { market: 'nazimabad', day: 3, start: '16:00', end: '20:00' },
      { market: 'nazimabad', day: 6, start: '16:00', end: '20:00' },
      { market: 'saddar', day: 4, start: '07:00', end: '11:00' },
    ],
    cutoff: 6,
    products: [
      { name: 'Fresh Mint (Podina)', cat: 'herbs', price: 60, unit: 'bunch', qty: 80, img: 'herb', desc: 'Fragrant mint for chutney, raita and mint lemonade.' },
      { name: 'Coriander (Dhania)', cat: 'herbs', price: 50, unit: 'bunch', qty: 90, img: 'herb', desc: 'Tender coriander with roots on for longer freshness.' },
      { name: 'Baby Spinach', cat: 'herbs', price: 160, was: 200, unit: 'bunch', qty: 40, img: 'leafy-greens', desc: 'Young spinach leaves, washed and bunched.' },
      { name: 'Iceberg Lettuce', cat: 'herbs', price: 220, unit: 'piece', qty: 20, img: 'leafy-greens', desc: 'Crisp lettuce heads for salads and burgers.' },
      { name: 'Broccoli', cat: 'veg', price: 450, was: 640, unit: 'kg', qty: 15, img: 'broccoli', desc: 'Dense green broccoli crowns.' },
      { name: 'Button Mushrooms', cat: 'veg', price: 700, unit: 'pack', qty: 0, img: 'mushroom', desc: '400 g pack of white button mushrooms. Sold out this week.', template: 15 },
    ],
  },
  {
    key: 'honey',
    email: 'honey@marketlink.com',
    status: 'active',
    stallName: 'Kirthar Honey & Preserves',
    contactPerson: 'Nadia Baloch',
    phone: '+92 312 9990011',
    address: 'Kirthar Range Apiaries, Jamshoro',
    city: 'Karachi',
    bio: 'Wild Sidr and acacia honey from our hives in the Kirthar foothills, plus small-batch jams and chutneys made from market surplus.',
    bioUr: "کیرتھر کے دامن میں ہمارے چھتوں سے جنگلی بیری اور پھلاہی کا شہد، اور مارکیٹ کے بچے ہوئے پھلوں سے تھوڑی مقدار میں بنے جام اور چٹنیاں۔",
    tags: ['Raw honey', 'Zero waste'],
    logo: thumb('acacia-honey'),
    cover: '/uploads/places/farms/honey.webp',
    latitude: 24.7928,
    longitude: 67.0652,
    windows: [
      { market: 'dha', day: 5, start: '09:00', end: '13:00' },
      { market: 'gulshan', day: 0, start: '09:00', end: '13:00' },
    ],
    cutoff: 24,
    products: [
      { name: 'Wild Sidr Honey', cat: 'honey', price: 3200, unit: 'jar', qty: 20, img: 'honey', desc: '500 g of raw, unfiltered Sidr (beri) honey.' },
      { name: 'Acacia Honey', cat: 'honey', price: 2200, unit: 'jar', qty: 25, img: 'honey', desc: '500 g light, floral acacia honey.' },
      { name: 'Strawberry Jam', cat: 'honey', price: 750, unit: 'jar', qty: 18, img: 'strawberry', desc: 'Small-batch jam with 70% fruit.' },
      { name: 'Mango Chutney', cat: 'honey', price: 650, unit: 'jar', qty: 14, img: 'jar', desc: 'Sweet and tangy chutney made from raw mangoes.' },
      { name: 'Green Olives in Brine', cat: 'honey', price: 950, unit: 'jar', qty: 10, img: 'olive', desc: 'Hand-picked olives cured in salt brine.' },
    ],
  },
  {
    key: 'grains',
    email: 'grains@marketlink.com',
    status: 'active',
    stallName: 'Indus Grains & Pulses',
    contactPerson: 'Kamran Shah',
    phone: '+92 322 3334455',
    address: 'Grain Market Road, Nawabshah',
    city: 'Karachi',
    bio: 'Stone-ground atta, aged basmati and home-cleaned pulses from farms along the Indus.',
    bioUr: "دریائے سندھ کے کنارے کے کھیتوں سے چکی کا پسا آٹا، پرانا باسمتی اور گھر میں صاف کی ہوئی دالیں۔",
    tags: ['Stone-ground', 'Bulk friendly'],
    logo: thumb('aged-basmati-rice'),
    cover: '/uploads/places/farms/grains.webp',
    latitude: 24.8601,
    longitude: 67.0305,
    windows: [
      { market: 'saddar', day: 1, start: '07:00', end: '11:00' },
      { market: 'saddar', day: 6, start: '07:00', end: '11:00' },
      { market: 'nazimabad', day: 3, start: '17:00', end: '20:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Chakki Atta (5 kg)', cat: 'grains', price: 1100, unit: 'pack', qty: 40, img: 'wheat', desc: 'Stone-ground whole wheat flour in a 5 kg bag.' },
      { name: 'Aged Basmati Rice', cat: 'grains', price: 420, unit: 'kg', qty: 100, img: 'rice', desc: 'Two-year aged basmati with long, fragrant grains.' },
      { name: 'Red Kidney Beans', cat: 'grains', price: 480, unit: 'kg', qty: 30, img: 'beans', desc: 'Cleaned rajma beans.' },
      { name: 'Roasted Peanuts', cat: 'grains', price: 600, unit: 'kg', qty: 25, img: 'peanuts', desc: 'Sand-roasted peanuts, a winter favourite.' },
      { name: 'Green Peas (Matar)', cat: 'veg', price: 220, was: 260, unit: 'kg', qty: 35, img: 'peas', desc: 'Sweet green peas in the pod.' },
    ],
  },
  {
    key: 'bloom',
    email: 'nursery@marketlink.com',
    status: 'active',
    stallName: 'Bloom & Bough Nursery',
    contactPerson: 'Hina Farooq',
    phone: '+92 331 6667788',
    address: 'Nursery Row, Shahrah-e-Faisal, Karachi',
    city: 'Karachi',
    bio: 'Cut flowers and easy-care houseplants grown in our shade houses along the Faisal nursery belt.',
    bioUr: "فیصل نرسری بیلٹ پر ہمارے سایہ دار گھروں میں اگائے گئے تازہ کٹے پھول اور آسانی سے پلنے والے گھریلو پودے۔",
    tags: ['Flowers', 'Houseplants'],
    logo: thumb('sunflower-bunch'),
    cover: '/uploads/places/farms/bloom.webp',
    latitude: 24.8826,
    longitude: 67.0704,
    windows: [
      { market: 'clifton', day: 0, start: '08:00', end: '12:00' },
      { market: 'bahadurabad', day: 5, start: '16:00', end: '20:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Sunflower Bunch', cat: 'flowers', price: 900, unit: 'bunch', qty: 15, img: 'sunflower', desc: 'Five bright sunflowers to light up any room.' },
      { name: 'Desi Rose Bouquet', cat: 'flowers', price: 700, unit: 'bunch', qty: 20, img: 'rose', desc: 'A dozen fragrant desi gulab roses.' },
      { name: 'Tulip Bunch', cat: 'flowers', price: 1500, unit: 'bunch', qty: 8, img: 'tulip', desc: 'Ten greenhouse tulips in mixed colours.' },
      { name: 'Money Plant (Potted)', cat: 'flowers', price: 850, unit: 'piece', qty: 12, img: 'potted-plant', desc: 'Easy-care pothos in a 6-inch pot.' },
      { name: 'Mini Cactus', cat: 'flowers', price: 450, unit: 'piece', qty: 18, img: 'cactus', desc: 'Cute desk cactus in a clay pot.' },
      { name: 'Hibiscus Plant', cat: 'flowers', price: 1100, unit: 'piece', qty: 6, img: 'hibiscus', desc: 'Flowering gurhal plant for your balcony.' },
    ],
  },
  {
    key: 'modeltown',
    email: 'lahore.farm@marketlink.com',
    status: 'active',
    stallName: 'Ravi Organic Farm',
    contactPerson: 'Ali Hamza',
    phone: '+92 302 1112233',
    address: 'Raiwind Road Farms, Lahore',
    city: 'Lahore',
    bio: 'A family farm near Raiwind that follows organic practices, growing strawberries, kinnow and winter vegetables for Lahore families.',
    bioUr: "رائے ونڈ کے قریب ایک خاندانی فارم جو نامیاتی طریقوں پر عمل کرتا ہے اور لاہور کے خاندانوں کے لیے اسٹرابیری، کینو اور سردیوں کی سبزیاں اگاتا ہے۔",
    tags: ['Organic practices', 'Winter crops'],
    logo: thumb('strawberries'),
    cover: '/uploads/places/farms/modeltown.webp',
    latitude: 31.4846,
    longitude: 74.3252,
    windows: [
      { market: 'lahore', day: 0, start: '07:00', end: '12:00' },
      { market: 'lahore', day: 4, start: '08:00', end: '12:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Strawberries', cat: 'fruit', price: 600, unit: 'box', qty: 30, img: 'strawberry', desc: '500 g box of sweet Lahore strawberries.' },
      { name: 'Kinnow Oranges', cat: 'fruit', price: 320, unit: 'dozen', qty: 40, img: 'orange', desc: 'Juicy kinnow straight from Sargodha partners.' },
      { name: 'Sweet Potatoes', cat: 'veg', price: 160, unit: 'kg', qty: 35, img: 'sweet-potato', desc: 'Roast them on coals for the perfect winter snack.' },
      { name: 'Sweet Corn', cat: 'veg', price: 80, was: 100, unit: 'piece', qty: 50, img: 'corn', desc: 'Tender sweet corn cobs.' },
      { name: 'Garlic', cat: 'veg', price: 600, unit: 'kg', qty: 20, img: 'garlic', desc: 'Pungent desi garlic bulbs.' },
      { name: 'Fresh Ginger', cat: 'veg', price: 700, unit: 'kg', qty: 15, img: 'ginger', desc: 'Aromatic ginger root.' },
    ],
  },
  {
    key: 'margalla',
    email: 'islamabad.farm@marketlink.com',
    status: 'active',
    stallName: 'Margalla Hills Farm',
    contactPerson: 'Mehwish Abbasi',
    phone: '+92 305 8889900',
    address: 'Shahdara Valley, Islamabad',
    city: 'Islamabad',
    bio: 'Hillside orchards above Islamabad with apples, peaches, cherries and kiwi from our partner farms in Swat.',
    bioUr: "اسلام آباد کے اوپر پہاڑی باغات، اور سوات میں ہمارے شراکت دار فارموں سے سیب، آڑو، چیری اور کیوی۔",
    tags: ['Hill fruit', 'Orchard'],
    logo: thumb('red-apples'),
    cover: '/uploads/places/farms/margalla.webp',
    latitude: 33.7024,
    longitude: 73.0271,
    windows: [
      { market: 'islamabad', day: 6, start: '08:00', end: '13:00' },
      { market: 'islamabad', day: 0, start: '08:00', end: '13:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Red Apples', cat: 'fruit', price: 380, was: 450, unit: 'kg', qty: 60, img: 'apple', desc: 'Crisp red apples from Swat.' },
      { name: 'Green Apples', cat: 'fruit', price: 420, unit: 'kg', qty: 30, img: 'green-apple', desc: 'Tart green apples for baking and snacking.' },
      { name: 'Peaches', cat: 'fruit', price: 450, unit: 'kg', qty: 25, img: 'peach', desc: 'Soft, fragrant hill peaches.' },
      { name: 'Cherries', cat: 'fruit', price: 1200, unit: 'kg', qty: 10, img: 'cherries', desc: 'Dark sweet cherries, short season only.' },
      { name: 'Kiwi', cat: 'fruit', price: 900, unit: 'kg', qty: 12, img: 'kiwi', desc: 'Tangy kiwis from Swat valley.' },
      { name: 'Pears', cat: 'fruit', price: 350, unit: 'kg', qty: 20, img: 'pear', desc: 'Juicy nashpati pears.' },
    ],
  },
  {
    key: 'poultry',
    email: 'pending.farmer@marketlink.com',
    status: 'pending',
    stallName: 'Sunny Acres Poultry',
    contactPerson: 'Rashid Mehmood',
    phone: '+92 311 2020202',
    address: 'Super Highway, Karachi',
    city: 'Karachi',
    bio: 'Free-range chicken and eggs. Waiting for approval.',
    bioUr: "کھلے میں پلی مرغیاں اور انڈے۔ منظوری کا انتظار ہے۔",
    tags: ['Free-range'],
    logo: thumb('desi-eggs'),
    cover: '/uploads/places/farms/poultry.webp',
    latitude: 24.93,
    longitude: 67.1,
    windows: [{ market: 'gulshan', day: 0, start: '08:00', end: '12:00' }],
    cutoff: 12,
    products: [],
  },
  {
    key: 'goat',
    email: 'suspended.farmer@marketlink.com',
    status: 'suspended',
    stallName: 'Old Town Goat Dairy',
    contactPerson: 'Jawad Iqbal',
    phone: '+92 313 4040404',
    address: 'Lyari, Karachi',
    city: 'Karachi',
    bio: 'Goat milk and cheese. Suspended for repeated late cancellations.',
    bioUr: "بکری کا دودھ اور پنیر۔ بار بار تاخیر سے منسوخی کی وجہ سے معطل۔",
    tags: ['Goat milk'],
    logo: thumb('goat-milk'),
    cover: '/uploads/places/farms/goat.webp',
    latitude: 24.87,
    longitude: 67.0,
    windows: [{ market: 'saddar', day: 1, start: '07:00', end: '10:00' }],
    cutoff: 12,
    products: [{ name: 'Goat Milk', cat: 'dairy', price: 300, unit: 'litre', qty: 10, img: 'milk', desc: 'Fresh goat milk.' }],
  },
];

// status: active | inactive. `household` links family members (optional family sharing).
export const customers = [
  { key: 'ayesha', name: 'Ayesha Khan', email: 'customer@marketlink.com', phone: '+92 300 9876543', address: 'Flat 4B, Sea Breeze Apartments, Clifton Block 2, Karachi', city: 'Karachi' },
  { key: 'omar', name: 'Omar Khan', email: 'omar@marketlink.com', phone: '+92 300 1239876', address: 'Flat 4B, Sea Breeze Apartments, Clifton Block 2, Karachi', city: 'Karachi', household: 'ayesha' },
  { key: 'bilal', name: 'Bilal Ahmed', email: 'bilal@marketlink.com', phone: '+92 321 7654321', address: 'House 22, Street 5, DHA Phase 6, Karachi', city: 'Karachi' },
  { key: 'sara', name: 'Sara Ali', email: 'sara@marketlink.com', phone: '+92 333 1122334', address: 'Block 13-D, Gulshan-e-Iqbal, Karachi', city: 'Karachi' },
  { key: 'usman', name: 'Usman Tariq', email: 'usman@marketlink.com', phone: '+92 345 5566778', address: 'Block H, North Nazimabad, Karachi', city: 'Karachi' },
  { key: 'fatima', name: 'Fatima Noor', email: 'fatima@marketlink.com', phone: '+92 302 9988776', address: 'Model Town, Lahore', city: 'Lahore' },
  { key: 'hamza', name: 'Hamza Sheikh', email: 'hamza@marketlink.com', phone: '+92 305 4433221', address: 'F-10 Markaz, Islamabad', city: 'Islamabad' },
  { key: 'inactive', name: 'Kashif Javed', email: 'inactive.customer@marketlink.com', phone: '+92 310 0001112', address: 'Saddar, Karachi', city: 'Karachi', status: 'inactive' },
];

export const reviewComments = {
  5: [
    'Absolutely fresh, tasted like it was picked this morning!',
    'Best quality I have found in Karachi. Will order every week.',
    'Pre-order was ready on time and the stall owner was so friendly.',
    'Amazing flavour, my family loved it.',
    'Worth every rupee. Packed neatly and super fresh.',
    'No more rushing to the market at 7 am. My order was packed and waiting for me.',
    'Paying at the stall is so easy, and the farmer even added a free bunch of mint.',
    'Much fresher than the supermarket and the price is fair.',
    'I love knowing exactly which farm my food comes from.',
    'Ordered on Thursday night, picked it up on Saturday morning. Perfect.',
    'My mother was very happy with the quality. We will keep ordering.',
  ],
  4: [
    'Very good quality, slightly smaller than last time.',
    'Fresh and tasty. Pickup was quick and easy.',
    'Great produce, would love more variety next week.',
    'Good value and the slot system saved me a lot of time.',
    'Lovely produce. The pickup slot made the market visit quick.',
    'Fresh and well sorted, I only wish the stall opened a little earlier.',
  ],
  3: ['Decent, but a few pieces were bruised.', 'Okay quality, pickup queue was a bit long.'],
  2: ['Not as fresh as expected this week.'],
};

export const farmerResponses = [
  'Thank you so much! See you at the market next week.',
  'We really appreciate your feedback. Happy cooking!',
  'Sorry about that, we will pack more carefully next time.',
  'Thanks for supporting local farmers!',
];

// Seasonal notices: each one shows only in its months (1 = January), so the banner always
// matches what is actually being harvested. Empty months = all year.
export const announcements = [
  {
    title: 'Winter harvest is here!',
    message: 'Kinnow from Sargodha, sweet carrots, green peas and fresh greens are at the markets now. Pre-order for Friday pickup.',
    titleUr: 'سردیوں کی فصل آ گئی!',
    messageUr: 'سرگودھا کے کینو، میٹھی گاجریں، ہرے مٹر اور تازہ سبزیاں اب مارکیٹوں میں ہیں۔ جمعہ کی وصولی کے لیے پیشگی آرڈر دیں۔',
    audience: 'all',
    months: [12, 1, 2],
    link: '/products?category=vegetables',
    isActive: true,
  },
  {
    title: 'Strawberry season is here!',
    message: 'Sweet Lahore strawberries and the first spring greens are in. Boxes sell out quickly, so pre-order early.',
    titleUr: 'اسٹرابیری کا موسم آ گیا!',
    messageUr: 'لاہور کی میٹھی اسٹرابیری اور بہار کی پہلی سبزیاں آ گئی ہیں۔ ڈبے جلدی ختم ہو جاتے ہیں، اس لیے جلد پیشگی آرڈر دیں۔',
    audience: 'all',
    months: [3, 4],
    link: '/products?category=fruits',
    isActive: true,
  },
  {
    title: 'Mango season is here!',
    message: 'Sindhri and Chaunsa mangoes are now available from Gadap Orchard Co. Pre-order early: they sell out by Sunday noon!',
    titleUr: 'آم کا موسم آ گیا!',
    messageUr: 'سندھڑی اور چونسا آم اب Gadap Orchard Co. کے پاس دستیاب ہیں۔ جلد پیشگی آرڈر دیں: اتوار کی دوپہر تک ختم ہو جاتے ہیں!',
    audience: 'all',
    months: [5, 6, 7, 8],
    link: '/products?category=fruits',
    isActive: true,
  },
  {
    title: 'Autumn harvest: apples and pears are in!',
    message: 'New-season Swat apples, juicy pears and kiwis from Margalla Hills Farm are at the markets this week. Pre-order for pickup.',
    titleUr: 'خزاں کی فصل: سیب اور ناشپاتیاں آ گئیں!',
    messageUr: 'Margalla Hills Farm سے سوات کے نئے موسم کے سیب، رس بھری ناشپاتیاں اور کیوی اس ہفتے مارکیٹوں میں ہیں۔ وصولی کے لیے پیشگی آرڈر دیں۔',
    audience: 'all',
    months: [9, 10, 11],
    link: '/products?category=fruits',
    isActive: true,
  },
  {
    title: 'Tip for farmers: use your weekly template',
    message: 'Set a weekly quantity for each product and MarketLink will refresh your stock automatically every Monday.',
    titleUr: 'کسانوں کے لیے مشورہ: ہفتہ وار سانچہ استعمال کریں',
    messageUr: 'ہر چیز کے لیے ہفتہ وار مقدار مقرر کریں، MarketLink ہر پیر کو آپ کا اسٹاک خود بخود تازہ کر دے گا۔',
    audience: 'farmer',
    isActive: true,
  },
];

// Newsletter sign-ups (the weekly harvest e-mail)
export const subscribers = [
  { email: 'customer@marketlink.com', name: 'Ayesha Khan', source: 'home' },
  { email: 'sara@marketlink.com', name: 'Sara Ali', source: 'footer' },
  { email: 'mariam@example.com', name: 'Mariam Siddiqui', source: 'footer' },
  { email: 'hamza@marketlink.com', name: 'Hamza Sheikh', source: 'checkout' },
  { email: 'zainab.r@example.com', source: 'home' },
  { email: 'ali.hassan@example.com', source: 'footer', status: 'unsubscribed', unsubscribedAt: new Date() },
];

export const contactMessages = [
  { name: 'Mariam Siddiqui', email: 'mariam@example.com', subject: 'Market in Hyderabad?', message: 'Do you plan to add a farmers market in Hyderabad? Would love to join as a customer.' },
  { name: 'Tariq Jamil', email: 'tariq@example.com', subject: 'Joining as a farmer', message: 'I grow citrus near Sargodha. How can I register my stall and which markets can I join?' },
];

// Urdu names of the demo products (shown when the site is in Urdu)
export const urduNames = {
  'Vine Tomatoes': 'بیل کے ٹماٹر',
  'Sweet Carrots': 'میٹھی گاجریں',
  'Farm Potatoes': 'فارم کے آلو',
  'Red Onions': 'لال پیاز',
  'Desi Cucumbers': 'دیسی کھیرے',
  'Purple Brinjal': 'جامنی بینگن',
  'Capsicum Mix': 'رنگ برنگی شملہ مرچ',
  'Green Chillies': 'ہری مرچیں',
  'Sindhri Mangoes': 'سندھڑی آم',
  'Chaunsa Mangoes': 'چونسا آم',
  Bananas: 'کیلے',
  Watermelon: 'تربوز',
  'Cantaloupe Melon': 'خربوزہ',
  'Tender Coconuts': 'کچے ناریل',
  Lemons: 'لیموں',
  'Fresh Buffalo Milk': 'بھینس کا تازہ دودھ',
  'Farm Paneer': 'فارم کا پنیر',
  'Desi Eggs': 'دیسی انڈے',
  'Hand-churned Butter': 'ہاتھ سے بلویا ہوا مکھن',
  'Natural Yogurt': 'خالص دہی',
  'Country Sourdough Loaf': 'ساؤر ڈو ڈبل روٹی',
  'Classic Baguette': 'کلاسک باگیٹ',
  'Butter Croissants': 'مکھن والے کروسان',
  'Whole Wheat Naan': 'گندم کے نان',
  'Sesame Bagels': 'تل والے بیگل',
  'Seasonal Fruit Pie': 'موسمی پھلوں کی پائی',
  'Oat Chocolate Cookies': 'جئی اور چاکلیٹ کی کوکیز',
  'Fresh Mint (Podina)': 'تازہ پودینہ',
  'Coriander (Dhania)': 'ہرا دھنیا',
  'Baby Spinach': 'نرم پتوں والی پالک',
  'Iceberg Lettuce': 'آئس برگ سلاد',
  Broccoli: 'بروکلی',
  'Button Mushrooms': 'بٹن مشروم',
  'Wild Sidr Honey': 'بیری کا جنگلی شہد',
  'Acacia Honey': 'پھلاہی کا شہد',
  'Strawberry Jam': 'اسٹرابیری جام',
  'Mango Chutney': 'آم کی چٹنی',
  'Green Olives in Brine': 'نمکین پانی میں ہرے زیتون',
  'Chakki Atta (5 kg)': 'چکی کا آٹا (5 کلو)',
  'Aged Basmati Rice': 'پرانے باسمتی چاول',
  'Red Kidney Beans': 'لال لوبیا (راجما)',
  'Roasted Peanuts': 'بھنی ہوئی مونگ پھلی',
  'Green Peas (Matar)': 'ہرے مٹر',
  'Sunflower Bunch': 'سورج مکھی کے پھول',
  'Desi Rose Bouquet': 'دیسی گلاب کا گلدستہ',
  'Tulip Bunch': 'ٹیولپ کے پھول',
  'Money Plant (Potted)': 'منی پلانٹ (گملے میں)',
  'Mini Cactus': 'چھوٹا کیکٹس',
  'Hibiscus Plant': 'گڑہل کا پودا',
  Strawberries: 'اسٹرابیری',
  'Kinnow Oranges': 'کینو',
  'Sweet Potatoes': 'شکر قندی',
  'Sweet Corn': 'میٹھی مکئی',
  Garlic: 'لہسن',
  'Fresh Ginger': 'تازہ ادرک',
  'Red Apples': 'لال سیب',
  'Green Apples': 'ہرے سیب',
  Peaches: 'آڑو',
  Cherries: 'چیری',
  Kiwi: 'کیوی',
  Pears: 'ناشپاتی',
  'Goat Milk': 'بکری کا دودھ',
};

// Urdu descriptions of the demo products (shown when the site is in Urdu)
export const urduDescriptions = {
  "Vine Tomatoes": "بیل پر پکے ہوئے رس بھرے لال ٹماٹر۔ سلاد، کڑاہی اور چٹنی کے لیے بہترین۔",
  "Sweet Carrots": "سردیوں کی کرکری گاجریں، گاجر کے حلوے یا تازہ جوس کے لیے بہترین۔",
  "Farm Potatoes": "ہر کام کے آلو، دھلے ہوئے اور چھانٹے ہوئے۔",
  "Red Onions": "ہمارے خشک کھیتوں کے تیز اور ذائقہ دار لال پیاز۔",
  "Desi Cucumbers": "پتلے چھلکے والے چھوٹے کرکرے کھیرے۔ رائتے کے لیے بہترین۔",
  "Purple Brinjal": "چمکدار گول بینگن، بھرتے اور تلے ہوئے بینگن کے لیے بہترین۔",
  "Capsicum Mix": "ہری اور لال شملہ مرچ۔ اس ہفتے ختم ہے، اگلی فصل میں دوبارہ آئے گی۔",
  "Green Chillies": "تازہ توڑی ہوئی تیز ہری مرچیں۔",
  "Sindhri Mangoes": "پھلوں کا بادشاہ۔ میٹھے، بغیر ریشے کے سندھڑی آم۔",
  "Chaunsa Mangoes": "موسم کے آخر کا چونسا، شہد جیسی بھرپور مٹھاس کے ساتھ۔",
  "Bananas": "دریا کنارے ہمارے کھیتوں کے قدرتی طور پر پکے کیلے۔",
  "Watermelon": "گرمیوں کے کرکرے اور میٹھے تربوز۔",
  "Cantaloupe Melon": "خوشبودار خربوزے، ناشتے کے لیے بہترین۔",
  "Tender Coconuts": "میٹھے پانی سے بھرے تازہ ناریل۔",
  "Lemons": "سکنجبین کے لیے رس بھرے دیسی لیموں۔",
  "Fresh Buffalo Milk": "بھینس کا گاڑھا خالص دودھ، دوہتے ہی ٹھنڈا کیا گیا۔",
  "Farm Paneer": "اسی صبح بنا نرم پنیر۔ پالک پنیر کے لیے بہترین۔",
  "Desi Eggs": "کھلے میں پلی مرغیوں کے دیسی انڈے، گہری نارنجی زردی کے ساتھ۔",
  "Hand-churned Butter": "روایتی مکھن، ہلکا نمکین، 250 گرام کا پیکٹ۔",
  "Natural Yogurt": "مٹی کے برتنوں میں رات بھر جمایا گیا گاڑھا دہی۔",
  "Country Sourdough Loaf": "36 گھنٹے خمیر کی ہوئی ساؤر ڈو روٹی، کرکری پرت کے ساتھ۔",
  "Classic Baguette": "کرکرا اور ہلکا پھلکا فرانسیسی باگیٹ۔",
  "Butter Croissants": "خالص مکھن والے 4 خستہ کروسان کا ڈبہ۔",
  "Whole Wheat Naan": "گندم کے 6 نرم نان کا پیکٹ۔",
  "Sesame Bagels": "تل والے 4 نرم بیگل کا پیکٹ۔",
  "Seasonal Fruit Pie": "مکھن والی پائی، اس ہفتے کے پھلوں سے بھری ہوئی۔",
  "Oat Chocolate Cookies": "جئی اور ڈارک چاکلیٹ کی 6 کوکیز کا ڈبہ۔",
  "Fresh Mint (Podina)": "چٹنی، رائتے اور پودینے والے لیموں پانی کے لیے خوشبودار پودینہ۔",
  "Coriander (Dhania)": "جڑوں سمیت نرم ہرا دھنیا، تاکہ دیر تک تازہ رہے۔",
  "Baby Spinach": "پالک کے نرم پتے، دھلے ہوئے اور گٹھیوں میں بندھے ہوئے۔",
  "Iceberg Lettuce": "سلاد اور برگر کے لیے کرکری سلاد پتا۔",
  "Broccoli": "گھنی اور ہری بروکلی۔",
  "Button Mushrooms": "سفید بٹن مشروم کا 400 گرام پیکٹ۔ اس ہفتے ختم ہے۔",
  "Wild Sidr Honey": "500 گرام خالص، بغیر چھانا بیری کا شہد۔",
  "Acacia Honey": "500 گرام ہلکا اور پھولوں کی خوشبو والا پھلاہی کا شہد۔",
  "Strawberry Jam": "تھوڑی مقدار میں بنا جام، 70% پھل کے ساتھ۔",
  "Mango Chutney": "کچے آموں سے بنی کھٹی میٹھی چٹنی۔",
  "Green Olives in Brine": "ہاتھ سے چنے ہوئے زیتون، نمکین پانی میں تیار کیے گئے۔",
  "Chakki Atta (5 kg)": "5 کلو کے تھیلے میں چکی کا پسا گندم کا آٹا۔",
  "Aged Basmati Rice": "دو سال پرانے باسمتی چاول، لمبے اور خوشبودار دانوں کے ساتھ۔",
  "Red Kidney Beans": "صاف کیا ہوا لال لوبیا (راجما)۔",
  "Roasted Peanuts": "ریت میں بھنی ہوئی مونگ پھلی، سردیوں کی پسندیدہ۔",
  "Green Peas (Matar)": "پھلیوں میں میٹھے ہرے مٹر۔",
  "Sunflower Bunch": "سورج مکھی کے پانچ چمکدار پھول جو ہر کمرے کو روشن کر دیں۔",
  "Desi Rose Bouquet": "ایک درجن خوشبودار دیسی گلاب۔",
  "Tulip Bunch": "ملے جلے رنگوں کے دس ٹیولپ، گرین ہاؤس میں اگائے گئے۔",
  "Money Plant (Potted)": "6 انچ کے گملے میں آسانی سے پلنے والا منی پلانٹ۔",
  "Mini Cactus": "مٹی کے گملے میں میز پر رکھنے والا پیارا سا کیکٹس۔",
  "Hibiscus Plant": "آپ کی بالکونی کے لیے پھول دار گڑہل کا پودا۔",
  "Strawberries": "لاہور کی میٹھی اسٹرابیری کا 500 گرام ڈبہ۔",
  "Kinnow Oranges": "سرگودھا کے شراکت داروں سے سیدھے رس بھرے کینو۔",
  "Sweet Potatoes": "انہیں کوئلوں پر بھونیں، سردیوں کا بہترین ناشتہ۔",
  "Sweet Corn": "نرم اور میٹھی مکئی کے بھٹے۔",
  "Garlic": "تیز خوشبو والا دیسی لہسن۔",
  "Fresh Ginger": "خوشبودار تازہ ادرک۔",
  "Red Apples": "سوات کے کرکرے لال سیب۔",
  "Green Apples": "بیکنگ اور ویسے کھانے کے لیے کھٹے ہرے سیب۔",
  "Peaches": "پہاڑوں کے نرم اور خوشبودار آڑو۔",
  "Cherries": "گہری رنگت والی میٹھی چیری، صرف تھوڑے سے موسم کے لیے۔",
  "Kiwi": "وادیٔ سوات کی کھٹی میٹھی کیوی۔",
  "Pears": "رس بھری ناشپاتیاں۔",
  "Goat Milk": "بکری کا تازہ دودھ۔"
};
