// Demo data used by `npm run seed`.
// Images are 3D illustrations from Microsoft Fluent Emoji (MIT licence) stored in /uploads/seed.

const img = (name) => `/uploads/seed/${name}.webp`;

export const PASSWORDS = {
  admin: 'Admin@123',
  farmer: 'Farmer@123',
  customer: 'Customer@123',
};

export const admin = { name: 'MarketLink Admin', email: 'admin@marketlink.com', phone: '+92 300 0000000', address: 'MarketLink HQ, Shahrah-e-Faisal, Karachi', city: 'Karachi' };

export const categories = [
  { key: 'veg', name: 'Vegetables', description: 'Seasonal vegetables harvested for market day.', icon: img('carrot'), color: '#E4F3D8', sortOrder: 1 },
  { key: 'fruit', name: 'Fruits', description: 'Orchard-fresh and tree-ripened fruit.', icon: img('apple'), color: '#FFE4DA', sortOrder: 2 },
  { key: 'dairy', name: 'Dairy & Eggs', description: 'Fresh milk, cheese, butter and free-range eggs.', icon: img('milk'), color: '#E3EEFB', sortOrder: 3 },
  { key: 'bakery', name: 'Baked Goods', description: 'Breads and treats baked the morning of the market.', icon: img('bread'), color: '#F8E8CF', sortOrder: 4 },
  { key: 'herbs', name: 'Herbs & Greens', description: 'Leafy greens and fragrant herbs.', icon: img('herb'), color: '#DAF1E3', sortOrder: 5 },
  { key: 'honey', name: 'Honey & Preserves', description: 'Raw honey, jams, chutneys and pickles.', icon: img('honey'), color: '#FFF0C2', sortOrder: 6 },
  { key: 'grains', name: 'Grains & Pulses', description: 'Stone-ground flour, rice, lentils and nuts.', icon: img('wheat'), color: '#F1EAD6', sortOrder: 7 },
  { key: 'flowers', name: 'Flowers & Plants', description: 'Cut flowers and potted plants.', icon: img('sunflower'), color: '#FBE1EE', sortOrder: 8 },
];

// Days: 0 = Sunday ... 6 = Saturday
export const markets = [
  {
    key: 'clifton',
    name: 'Clifton Seaview Farmers Market',
    description: 'A breezy weekend market near the sea front with the widest choice of vegetables, bakery and flowers in the city.',
    address: 'Block 2, Clifton (near Boat Basin), Karachi',
    city: 'Karachi',
    latitude: 24.8195,
    longitude: 67.0306,
    operatingDays: [6, 0],
    openTime: '07:00',
    closeTime: '13:00',
    image: img('basket'),
  },
  {
    key: 'dha',
    name: 'DHA Phase 6 Weekend Market',
    description: 'Friday and Sunday market in Bukhari Commercial, loved for dairy, honey and ready-to-eat bakes.',
    address: 'Bukhari Commercial, DHA Phase 6, Karachi',
    city: 'Karachi',
    latitude: 24.7934,
    longitude: 67.066,
    operatingDays: [5, 0],
    openTime: '08:00',
    closeTime: '14:00',
    image: img('tent'),
  },
  {
    key: 'gulshan',
    name: 'Gulshan Sunday Kisan Bazaar',
    description: 'A big, lively bazaar where farmers from Gadap and Malir bring fruit and vegetables straight from the field.',
    address: 'Block 13-D, Gulshan-e-Iqbal (near Maskan Chowrangi), Karachi',
    city: 'Karachi',
    latitude: 24.9206,
    longitude: 67.0935,
    operatingDays: [0, 3],
    openTime: '07:00',
    closeTime: '15:00',
    image: img('cart'),
  },
  {
    key: 'nazimabad',
    name: 'North Nazimabad Evening Green Market',
    description: 'An evening market for after-work shopping: herbs, greens, grains and pulses.',
    address: 'Block H, North Nazimabad (Hyderi), Karachi',
    city: 'Karachi',
    latitude: 24.9387,
    longitude: 67.0433,
    operatingDays: [3, 6],
    openTime: '16:00',
    closeTime: '21:00',
    image: img('hut'),
  },
  {
    key: 'bahadurabad',
    name: 'Bahadurabad Fresh Friday Market',
    description: 'Compact neighbourhood market around the Bahadurabad roundabout with fruit, flowers and bakery.',
    address: 'Bahadurabad Chowrangi, Bahadur Yar Jang Society, Karachi',
    city: 'Karachi',
    latitude: 24.8822,
    longitude: 67.0697,
    operatingDays: [2, 5],
    openTime: '16:00',
    closeTime: '21:00',
    image: img('store'),
  },
  {
    key: 'saddar',
    name: 'Saddar Heritage Farmers Market',
    description: 'Early-morning market near the historic Empress Market for grains, pulses and herbs.',
    address: 'Near Empress Market, Saddar, Karachi',
    city: 'Karachi',
    latitude: 24.8595,
    longitude: 67.0298,
    operatingDays: [1, 4, 6],
    openTime: '06:00',
    closeTime: '12:00',
    image: img('sunrise'),
  },
  {
    key: 'lahore',
    name: 'Model Town Kisan Market',
    description: 'Lahore\'s favourite Sunday and Thursday market for winter vegetables, strawberries and citrus.',
    address: 'Model Town Link Road, Lahore',
    city: 'Lahore',
    latitude: 31.484,
    longitude: 74.324,
    operatingDays: [0, 4],
    openTime: '07:00',
    closeTime: '13:00',
    image: img('camping'),
  },
  {
    key: 'islamabad',
    name: 'F-9 Park Weekend Market',
    description: 'Weekend market at the edge of F-9 Park with fruit from the Margalla and Murree hills.',
    address: 'Fatima Jinnah Park (F-9), Islamabad',
    city: 'Islamabad',
    latitude: 33.7016,
    longitude: 73.026,
    operatingDays: [6, 0],
    openTime: '08:00',
    closeTime: '14:00',
    image: img('tent'),
  },
];

// status: active (approved) | pending | suspended
export const farmers = [
  {
    key: 'malir',
    email: 'farmer@marketlink.com',
    status: 'active',
    stallName: 'Malir Green Fields',
    contactPerson: 'Ahmed Raza',
    phone: '+92 300 1234567',
    address: 'Plot 14, Malir Agricultural Belt, Karachi',
    city: 'Karachi',
    bio: 'Three generations of vegetable growers from Malir. We pick on Friday evening so everything is at its freshest for the weekend markets. No synthetic pesticides, just compost and care.',
    tags: ['Pesticide-free', 'Family farm', 'Picked daily'],
    logo: img('farmer-man'),
    latitude: 24.8203,
    longitude: 67.0318,
    windows: [
      { market: 'clifton', day: 6, start: '08:00', end: '12:00' },
      { market: 'clifton', day: 0, start: '08:00', end: '12:00' },
      { market: 'dha', day: 5, start: '09:00', end: '13:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Vine Tomatoes', cat: 'veg', price: 180, unit: 'kg', qty: 60, img: 'tomato', desc: 'Juicy red tomatoes ripened on the vine. Perfect for salads, karahi and chutneys.' },
      { name: 'Sweet Carrots', cat: 'veg', price: 120, unit: 'kg', qty: 45, img: 'carrot', desc: 'Crunchy winter carrots, great for gajar ka halwa or fresh juice.' },
      { name: 'Farm Potatoes', cat: 'veg', price: 90, unit: 'kg', qty: 80, img: 'potato', desc: 'Versatile all-purpose potatoes, washed and sorted.' },
      { name: 'Red Onions', cat: 'veg', price: 140, unit: 'kg', qty: 70, img: 'onion', desc: 'Sharp, flavourful red onions from our dry fields.' },
      { name: 'Desi Cucumbers', cat: 'veg', price: 100, unit: 'kg', qty: 30, img: 'cucumber', desc: 'Small, crisp cucumbers with thin skin. Great for raita.' },
      { name: 'Purple Brinjal', cat: 'veg', price: 110, unit: 'kg', qty: 25, img: 'eggplant', desc: 'Glossy round brinjals ideal for bharta and baingan fry.' },
      { name: 'Capsicum Mix', cat: 'veg', price: 320, unit: 'kg', qty: 0, img: 'bell-pepper', desc: 'Green and red bell peppers. Sold out this week, back next harvest.', template: 20 },
      { name: 'Green Chillies', cat: 'veg', price: 240, unit: 'kg', qty: 12, img: 'chilli', desc: 'Fiery green chillies, freshly picked.' },
    ],
  },
  {
    key: 'gadap',
    email: 'orchard@marketlink.com',
    status: 'active',
    stallName: 'Gadap Orchard Co.',
    contactPerson: 'Zainab Hussain',
    phone: '+92 321 5550101',
    address: 'Gadap Town Orchards, Karachi',
    city: 'Karachi',
    bio: 'Mango, banana and melon orchards in the Gadap valley. We tree-ripen our fruit and bring it to market within a day of picking.',
    tags: ['Tree-ripened', 'Orchard'],
    logo: img('farmer-woman'),
    latitude: 24.9214,
    longitude: 67.0948,
    windows: [
      { market: 'gulshan', day: 0, start: '08:00', end: '13:00' },
      { market: 'gulshan', day: 3, start: '08:00', end: '12:00' },
      { market: 'bahadurabad', day: 5, start: '16:00', end: '20:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Sindhri Mangoes', cat: 'fruit', price: 350, unit: 'kg', qty: 90, img: 'mango', desc: 'The king of fruits. Sweet, fibre-less Sindhri mangoes.' },
      { name: 'Chaunsa Mangoes', cat: 'fruit', price: 400, unit: 'kg', qty: 40, img: 'mango', desc: 'Late-season Chaunsa with rich, honey-like sweetness.' },
      { name: 'Bananas', cat: 'fruit', price: 180, unit: 'dozen', qty: 50, img: 'banana', desc: 'Naturally ripened bananas from our riverside plots.' },
      { name: 'Watermelon', cat: 'fruit', price: 70, unit: 'kg', qty: 35, img: 'watermelon', desc: 'Crisp and sweet summer watermelons.' },
      { name: 'Cantaloupe Melon', cat: 'fruit', price: 150, unit: 'piece', qty: 20, img: 'melon', desc: 'Fragrant melons, perfect for breakfast.' },
      { name: 'Tender Coconuts', cat: 'fruit', price: 200, unit: 'piece', qty: 15, img: 'coconut', desc: 'Fresh coconuts full of sweet water.' },
      { name: 'Lemons', cat: 'fruit', price: 260, unit: 'kg', qty: 18, img: 'lemon', desc: 'Juicy desi lemons for sikanjabeen.' },
    ],
  },
  {
    key: 'thatta',
    email: 'dairy@marketlink.com',
    status: 'active',
    stallName: 'Thatta Dairy Collective',
    contactPerson: 'Imran Soomro',
    phone: '+92 333 7778899',
    address: 'Village Jhimpir Road, Thatta, Sindh',
    city: 'Karachi',
    bio: 'A cooperative of twelve small dairy families. Grass-fed buffalo and cow milk, fresh paneer and free-range eggs delivered to market on ice.',
    tags: ['Cooperative', 'Grass-fed', 'Free-range'],
    logo: img('cow'),
    latitude: 24.7942,
    longitude: 67.0671,
    windows: [
      { market: 'dha', day: 5, start: '08:00', end: '12:00' },
      { market: 'dha', day: 0, start: '08:00', end: '12:00' },
      { market: 'clifton', day: 6, start: '08:00', end: '11:00' },
    ],
    cutoff: 24,
    products: [
      { name: 'Fresh Buffalo Milk', cat: 'dairy', price: 240, unit: 'litre', qty: 60, img: 'milk', desc: 'Creamy, unhomogenised buffalo milk, chilled at milking.' },
      { name: 'Farm Paneer', cat: 'dairy', price: 1400, unit: 'kg', qty: 10, img: 'cheese', desc: 'Soft paneer made the same morning. Perfect for palak paneer.' },
      { name: 'Desi Eggs', cat: 'dairy', price: 450, unit: 'dozen', qty: 40, img: 'egg', desc: 'Free-range desi eggs with deep orange yolks.' },
      { name: 'Hand-churned Butter', cat: 'dairy', price: 900, unit: 'pack', qty: 15, img: 'butter', desc: 'Traditional makhan, lightly salted, 250 g pack.' },
      { name: 'Natural Yogurt', cat: 'dairy', price: 280, unit: 'kg', qty: 25, img: 'jar', desc: 'Thick set dahi cultured overnight in clay pots.' },
    ],
  },
  {
    key: 'bakehouse',
    email: 'bakery@marketlink.com',
    status: 'active',
    stallName: 'Karachi Artisan Bakehouse',
    contactPerson: 'Sana Mirza',
    phone: '+92 345 2223344',
    address: 'Shop 7, Khayaban-e-Shamsheer, DHA Phase 5, Karachi',
    city: 'Karachi',
    bio: 'Slow-fermented sourdough and French-style pastries baked in small batches before sunrise. We use locally milled flour and Thatta butter.',
    tags: ['Sourdough', 'Small batch'],
    logo: img('croissant'),
    latitude: 24.8188,
    longitude: 67.0296,
    windows: [
      { market: 'clifton', day: 6, start: '08:00', end: '12:00' },
      { market: 'clifton', day: 0, start: '08:00', end: '12:00' },
      { market: 'bahadurabad', day: 2, start: '16:00', end: '20:00' },
    ],
    cutoff: 18,
    products: [
      { name: 'Country Sourdough Loaf', cat: 'bakery', price: 950, unit: 'loaf', qty: 20, img: 'bread', desc: '36-hour fermented sourdough with a crackly crust.' },
      { name: 'Classic Baguette', cat: 'bakery', price: 450, unit: 'piece', qty: 25, img: 'baguette', desc: 'Crisp, airy French baguette.' },
      { name: 'Butter Croissants', cat: 'bakery', price: 1200, unit: 'box', qty: 12, img: 'croissant', desc: 'Box of 4 flaky, all-butter croissants.' },
      { name: 'Whole Wheat Naan', cat: 'bakery', price: 300, unit: 'pack', qty: 30, img: 'flatbread', desc: 'Pack of 6 soft whole-wheat naans.' },
      { name: 'Sesame Bagels', cat: 'bakery', price: 800, unit: 'pack', qty: 10, img: 'bagel', desc: 'Pack of 4 chewy sesame bagels.' },
      { name: 'Seasonal Fruit Pie', cat: 'bakery', price: 1800, unit: 'piece', qty: 6, img: 'pie', desc: 'Buttery pie filled with fruit of the week.' },
      { name: 'Oat Chocolate Cookies', cat: 'bakery', price: 650, unit: 'box', qty: 15, img: 'cookie', desc: 'Box of 6 chewy oat and dark chocolate cookies.' },
    ],
  },
  {
    key: 'herbs',
    email: 'herbs@marketlink.com',
    status: 'active',
    stallName: 'Hyderabad Herb Garden',
    contactPerson: 'Farhan Qureshi',
    phone: '+92 301 4445566',
    address: 'Latifabad Unit 8, Hyderabad',
    city: 'Karachi',
    bio: 'Leafy greens and fragrant herbs grown in raised beds and harvested the same afternoon for the evening markets.',
    tags: ['Same-day harvest', 'Hydro-greens'],
    logo: img('herb'),
    latitude: 24.9395,
    longitude: 67.0441,
    windows: [
      { market: 'nazimabad', day: 3, start: '16:00', end: '20:00' },
      { market: 'nazimabad', day: 6, start: '16:00', end: '20:00' },
      { market: 'saddar', day: 4, start: '07:00', end: '11:00' },
    ],
    cutoff: 6,
    products: [
      { name: 'Fresh Mint (Podina)', cat: 'herbs', price: 60, unit: 'bunch', qty: 80, img: 'herb', desc: 'Fragrant mint for chutney, raita and mint lemonade.' },
      { name: 'Coriander (Dhania)', cat: 'herbs', price: 50, unit: 'bunch', qty: 90, img: 'herb', desc: 'Tender coriander with roots on for longer freshness.' },
      { name: 'Baby Spinach', cat: 'herbs', price: 160, unit: 'bunch', qty: 40, img: 'leafy-greens', desc: 'Young spinach leaves, washed and bunched.' },
      { name: 'Iceberg Lettuce', cat: 'herbs', price: 220, unit: 'piece', qty: 20, img: 'leafy-greens', desc: 'Crisp lettuce heads for salads and burgers.' },
      { name: 'Broccoli', cat: 'veg', price: 450, unit: 'kg', qty: 15, img: 'broccoli', desc: 'Dense green broccoli crowns.' },
      { name: 'Button Mushrooms', cat: 'veg', price: 700, unit: 'pack', qty: 0, img: 'mushroom', desc: '400 g pack of white button mushrooms. Sold out this week.', template: 15 },
    ],
  },
  {
    key: 'honey',
    email: 'honey@marketlink.com',
    status: 'active',
    stallName: 'Kirthar Honey & Preserves',
    contactPerson: 'Nadia Baloch',
    phone: '+92 312 9990011',
    address: 'Kirthar Range Apiaries, Jamshoro',
    city: 'Karachi',
    bio: 'Wild Sidr and acacia honey from our hives in the Kirthar foothills, plus small-batch jams and chutneys made from market surplus.',
    tags: ['Raw honey', 'Zero waste'],
    logo: img('bee'),
    latitude: 24.7928,
    longitude: 67.0652,
    windows: [
      { market: 'dha', day: 5, start: '09:00', end: '13:00' },
      { market: 'gulshan', day: 0, start: '09:00', end: '13:00' },
    ],
    cutoff: 24,
    products: [
      { name: 'Wild Sidr Honey', cat: 'honey', price: 3200, unit: 'jar', qty: 20, img: 'honey', desc: '500 g of raw, unfiltered Sidr (beri) honey.' },
      { name: 'Acacia Honey', cat: 'honey', price: 2200, unit: 'jar', qty: 25, img: 'honey', desc: '500 g light, floral acacia honey.' },
      { name: 'Strawberry Jam', cat: 'honey', price: 750, unit: 'jar', qty: 18, img: 'strawberry', desc: 'Small-batch jam with 70% fruit.' },
      { name: 'Mango Chutney', cat: 'honey', price: 650, unit: 'jar', qty: 14, img: 'jar', desc: 'Sweet and tangy chutney made from raw mangoes.' },
      { name: 'Green Olives in Brine', cat: 'honey', price: 950, unit: 'jar', qty: 10, img: 'olive', desc: 'Hand-picked olives cured in salt brine.' },
    ],
  },
  {
    key: 'grains',
    email: 'grains@marketlink.com',
    status: 'active',
    stallName: 'Indus Grains & Pulses',
    contactPerson: 'Kamran Shah',
    phone: '+92 322 3334455',
    address: 'Grain Market Road, Nawabshah',
    city: 'Karachi',
    bio: 'Stone-ground atta, aged basmati and home-cleaned pulses from farms along the Indus.',
    tags: ['Stone-ground', 'Bulk friendly'],
    logo: img('wheat'),
    latitude: 24.8601,
    longitude: 67.0305,
    windows: [
      { market: 'saddar', day: 1, start: '07:00', end: '11:00' },
      { market: 'saddar', day: 6, start: '07:00', end: '11:00' },
      { market: 'nazimabad', day: 3, start: '17:00', end: '20:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Chakki Atta (5 kg)', cat: 'grains', price: 1100, unit: 'pack', qty: 40, img: 'wheat', desc: 'Stone-ground whole wheat flour in a 5 kg bag.' },
      { name: 'Aged Basmati Rice', cat: 'grains', price: 420, unit: 'kg', qty: 100, img: 'rice', desc: 'Two-year aged basmati with long, fragrant grains.' },
      { name: 'Red Kidney Beans', cat: 'grains', price: 480, unit: 'kg', qty: 30, img: 'beans', desc: 'Cleaned rajma beans.' },
      { name: 'Roasted Peanuts', cat: 'grains', price: 600, unit: 'kg', qty: 25, img: 'peanuts', desc: 'Sand-roasted peanuts, a winter favourite.' },
      { name: 'Green Peas (Matar)', cat: 'veg', price: 220, unit: 'kg', qty: 35, img: 'peas', desc: 'Sweet green peas in the pod.' },
    ],
  },
  {
    key: 'bloom',
    email: 'nursery@marketlink.com',
    status: 'active',
    stallName: 'Bloom & Bough Nursery',
    contactPerson: 'Hina Farooq',
    phone: '+92 331 6667788',
    address: 'Nursery Row, Shahrah-e-Faisal, Karachi',
    city: 'Karachi',
    bio: 'Cut flowers and easy-care houseplants grown in our shade houses along the Faisal nursery belt.',
    tags: ['Flowers', 'Houseplants'],
    logo: img('sunflower'),
    latitude: 24.8826,
    longitude: 67.0704,
    windows: [
      { market: 'clifton', day: 0, start: '08:00', end: '12:00' },
      { market: 'bahadurabad', day: 5, start: '16:00', end: '20:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Sunflower Bunch', cat: 'flowers', price: 900, unit: 'bunch', qty: 15, img: 'sunflower', desc: 'Five bright sunflowers to light up any room.' },
      { name: 'Desi Rose Bouquet', cat: 'flowers', price: 700, unit: 'bunch', qty: 20, img: 'rose', desc: 'A dozen fragrant desi gulab roses.' },
      { name: 'Tulip Bunch', cat: 'flowers', price: 1500, unit: 'bunch', qty: 8, img: 'tulip', desc: 'Ten greenhouse tulips in mixed colours.' },
      { name: 'Money Plant (Potted)', cat: 'flowers', price: 850, unit: 'piece', qty: 12, img: 'potted-plant', desc: 'Easy-care pothos in a 6-inch pot.' },
      { name: 'Mini Cactus', cat: 'flowers', price: 450, unit: 'piece', qty: 18, img: 'cactus', desc: 'Cute desk cactus in a clay pot.' },
      { name: 'Hibiscus Plant', cat: 'flowers', price: 1100, unit: 'piece', qty: 6, img: 'hibiscus', desc: 'Flowering gurhal plant for your balcony.' },
    ],
  },
  {
    key: 'modeltown',
    email: 'lahore.farm@marketlink.com',
    status: 'active',
    stallName: 'Ravi Organic Farm',
    contactPerson: 'Ali Hamza',
    phone: '+92 302 1112233',
    address: 'Raiwind Road Farms, Lahore',
    city: 'Lahore',
    bio: 'A family farm near Raiwind that follows organic practices, growing strawberries, kinnow and winter vegetables for Lahore families.',
    tags: ['Organic practices', 'Winter crops'],
    logo: img('tractor'),
    latitude: 31.4846,
    longitude: 74.3252,
    windows: [
      { market: 'lahore', day: 0, start: '07:00', end: '12:00' },
      { market: 'lahore', day: 4, start: '08:00', end: '12:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Strawberries', cat: 'fruit', price: 600, unit: 'box', qty: 30, img: 'strawberry', desc: '500 g box of sweet Lahore strawberries.' },
      { name: 'Kinnow Oranges', cat: 'fruit', price: 320, unit: 'dozen', qty: 40, img: 'orange', desc: 'Juicy kinnow straight from Sargodha partners.' },
      { name: 'Sweet Potatoes', cat: 'veg', price: 160, unit: 'kg', qty: 35, img: 'sweet-potato', desc: 'Roast them on coals for the perfect winter snack.' },
      { name: 'Sweet Corn', cat: 'veg', price: 80, unit: 'piece', qty: 50, img: 'corn', desc: 'Tender sweet corn cobs.' },
      { name: 'Garlic', cat: 'veg', price: 600, unit: 'kg', qty: 20, img: 'garlic', desc: 'Pungent desi garlic bulbs.' },
      { name: 'Fresh Ginger', cat: 'veg', price: 700, unit: 'kg', qty: 15, img: 'ginger', desc: 'Aromatic ginger root.' },
    ],
  },
  {
    key: 'margalla',
    email: 'islamabad.farm@marketlink.com',
    status: 'active',
    stallName: 'Margalla Hills Farm',
    contactPerson: 'Mehwish Abbasi',
    phone: '+92 305 8889900',
    address: 'Shahdara Valley, Islamabad',
    city: 'Islamabad',
    bio: 'Hillside orchards above Islamabad with apples, peaches, cherries and kiwi from our partner farms in Swat.',
    tags: ['Hill fruit', 'Orchard'],
    logo: img('farmer'),
    latitude: 33.7024,
    longitude: 73.0271,
    windows: [
      { market: 'islamabad', day: 6, start: '08:00', end: '13:00' },
      { market: 'islamabad', day: 0, start: '08:00', end: '13:00' },
    ],
    cutoff: 12,
    products: [
      { name: 'Red Apples', cat: 'fruit', price: 380, unit: 'kg', qty: 60, img: 'apple', desc: 'Crisp red apples from Swat.' },
      { name: 'Green Apples', cat: 'fruit', price: 420, unit: 'kg', qty: 30, img: 'green-apple', desc: 'Tart green apples for baking and snacking.' },
      { name: 'Peaches', cat: 'fruit', price: 450, unit: 'kg', qty: 25, img: 'peach', desc: 'Soft, fragrant hill peaches.' },
      { name: 'Cherries', cat: 'fruit', price: 1200, unit: 'kg', qty: 10, img: 'cherries', desc: 'Dark sweet cherries, short season only.' },
      { name: 'Kiwi', cat: 'fruit', price: 900, unit: 'kg', qty: 12, img: 'kiwi', desc: 'Tangy kiwis from Swat valley.' },
      { name: 'Pears', cat: 'fruit', price: 350, unit: 'kg', qty: 20, img: 'pear', desc: 'Juicy nashpati pears.' },
    ],
  },
  {
    key: 'poultry',
    email: 'pending.farmer@marketlink.com',
    status: 'pending',
    stallName: 'Sunny Acres Poultry',
    contactPerson: 'Rashid Mehmood',
    phone: '+92 311 2020202',
    address: 'Super Highway, Karachi',
    city: 'Karachi',
    bio: 'Free-range chicken and eggs. Waiting for approval.',
    tags: ['Free-range'],
    logo: img('chicken'),
    latitude: 24.93,
    longitude: 67.1,
    windows: [{ market: 'gulshan', day: 0, start: '08:00', end: '12:00' }],
    cutoff: 12,
    products: [],
  },
  {
    key: 'goat',
    email: 'suspended.farmer@marketlink.com',
    status: 'suspended',
    stallName: 'Old Town Goat Dairy',
    contactPerson: 'Jawad Iqbal',
    phone: '+92 313 4040404',
    address: 'Lyari, Karachi',
    city: 'Karachi',
    bio: 'Goat milk and cheese. Suspended for repeated late cancellations.',
    tags: ['Goat milk'],
    logo: img('goat'),
    latitude: 24.87,
    longitude: 67.0,
    windows: [{ market: 'saddar', day: 1, start: '07:00', end: '10:00' }],
    cutoff: 12,
    products: [{ name: 'Goat Milk', cat: 'dairy', price: 300, unit: 'litre', qty: 10, img: 'milk', desc: 'Fresh goat milk.' }],
  },
];

// status: active | inactive. `household` links family members (optional family sharing).
export const customers = [
  { key: 'ayesha', name: 'Ayesha Khan', email: 'customer@marketlink.com', phone: '+92 300 9876543', address: 'Flat 4B, Sea Breeze Apartments, Clifton Block 2, Karachi', city: 'Karachi' },
  { key: 'omar', name: 'Omar Khan', email: 'omar@marketlink.com', phone: '+92 300 1239876', address: 'Flat 4B, Sea Breeze Apartments, Clifton Block 2, Karachi', city: 'Karachi', household: 'ayesha' },
  { key: 'bilal', name: 'Bilal Ahmed', email: 'bilal@marketlink.com', phone: '+92 321 7654321', address: 'House 22, Street 5, DHA Phase 6, Karachi', city: 'Karachi' },
  { key: 'sara', name: 'Sara Ali', email: 'sara@marketlink.com', phone: '+92 333 1122334', address: 'Block 13-D, Gulshan-e-Iqbal, Karachi', city: 'Karachi' },
  { key: 'usman', name: 'Usman Tariq', email: 'usman@marketlink.com', phone: '+92 345 5566778', address: 'Block H, North Nazimabad, Karachi', city: 'Karachi' },
  { key: 'fatima', name: 'Fatima Noor', email: 'fatima@marketlink.com', phone: '+92 302 9988776', address: 'Model Town, Lahore', city: 'Lahore' },
  { key: 'hamza', name: 'Hamza Sheikh', email: 'hamza@marketlink.com', phone: '+92 305 4433221', address: 'F-10 Markaz, Islamabad', city: 'Islamabad' },
  { key: 'inactive', name: 'Kashif Javed', email: 'inactive.customer@marketlink.com', phone: '+92 310 0001112', address: 'Saddar, Karachi', city: 'Karachi', status: 'inactive' },
];

export const reviewComments = {
  5: [
    'Absolutely fresh, tasted like it was picked this morning!',
    'Best quality I have found in Karachi. Will order every week.',
    'Pre-order was ready on time and the stall owner was so friendly.',
    'Amazing flavour, my family loved it.',
    'Worth every rupee. Packed neatly and super fresh.',
  ],
  4: [
    'Very good quality, slightly smaller than last time.',
    'Fresh and tasty. Pickup was quick and easy.',
    'Great produce, would love more variety next week.',
    'Good value and the slot system saved me a lot of time.',
  ],
  3: ['Decent, but a few pieces were bruised.', 'Okay quality, pickup queue was a bit long.'],
  2: ['Not as fresh as expected this week.'],
};

export const farmerResponses = [
  'Thank you so much! See you at the market next week.',
  'We really appreciate your feedback. Happy cooking!',
  'Sorry about that, we will pack more carefully next time.',
  'Thanks for supporting local farmers!',
];

export const announcements = [
  {
    title: 'Mango season is here! 🥭',
    message: 'Sindhri and Chaunsa mangoes are now available from Gadap Orchard Co. Pre-order early — they sell out by Sunday noon!',
    audience: 'all',
    isActive: true,
  },
  {
    title: 'Tip for farmers: use your weekly template',
    message: 'Set a weekly quantity for each product and MarketLink will refresh your stock automatically every Monday.',
    audience: 'farmer',
    isActive: true,
  },
];

export const contactMessages = [
  { name: 'Mariam Siddiqui', email: 'mariam@example.com', subject: 'Market in Hyderabad?', message: 'Do you plan to add a farmers market in Hyderabad? Would love to join as a customer.' },
  { name: 'Tariq Jamil', email: 'tariq@example.com', subject: 'Joining as a farmer', message: 'I grow citrus near Sargodha. How can I register my stall and which markets can I join?' },
];
